### ISSUE TITLE
ValueError: No taxon ID could be matched to any of the given gene IDs

### ISSUE THREAD

**Issue by thdurand4** [GuyTeichman/RNAlysis#30]
### Describe the bug

Hello,

I used your pipeline and everythings works well but when i want to use Enrichment analysis i got my enrichment set and my background set i got this error: "ValueError: No taxon ID could be matched to any of the given gene IDs"

Is it because genes of my organism are not in database Gene Ontology ? 

There is a way to execute Enrichment analysis if our genes are not referenced in the Gene ontology database ? 

### Steps To Reproduce

Enrichment Analysis

### How did you install RNAlysis?

Stand-alone app

### RNAlysis version

3.9.2

### Operating system

Linux

**Comment by GuyTeichman** [comment]
Hi,

The reason you encountered this error is probably because when running enrichment analysis, you set your organism to 'auto'. RNAlysis then tries to determine automatically which organism are you analyzing based on your gene names/IDs. In your case, this automatic detection step was not successful. 

Did you try setting the organism name/taxon ID manually? Which organism are you analyzing?

Best,
Guy.
